### ISSUE TITLE
Morning session: Peer-to-peer code review 11-10-2022

### ISSUE THREAD

**Issue by MuhmmdUsama** [tashisrael/JavaScript-testing-practice#1]

**Comment by tahseenzahra** [comment]
Good job so far @tashisrael 👍

I appreciate the approach that you used to solve the given task however you can also think of ways how to do that while minimizing the code lines.

**Comment by MuhmmdUsama** [comment]
# Status: Approved :green_circle:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

## Hey @tashisrael  :wave:

Great work on implementing the requirements. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:


:heavy_check_mark: Following Linters
✔️ Following the Requirements
✔️ Descriptive Readme
✔️ Following the GitFlow

# Optional
♻️: Something additional for your calculator task, To make your calculator more dynamic you can use the `reduce` method for your all operations to work with multi values, not just two values -- for example 
```
const Calculator = {
  add: (...num) => num.reduce((p, c) => p + c),
  sub: (...num) => num.reduce((p, c) => p - c),
  div: (...num) => num.reduce((p, c) => p / c),
  multi: (...num) => num.reduce((p, c) => p * c),
};

console.log(Calculator.add(10, 5,10,2))
console.log(Calculator.sub(10, 5,10,2))
console.log(Calculator.div(10, 5,10,2))
console.log(Calculator.multi(10, 5,10,2))

```

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the issue thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

---------------------------------------
